services:
  data-quality-presentation:
    container_name: web
    # The name of the image that will be created when building this container
    image: data-quality-presentation
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=development
      - TZ=America/Vancouver
    # Points to a file with the sensitive environment variables
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - frontend
networks:
  frontend:
    external: true
